version: '2.3'
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    image: cmpnet
    # environment:
      # - "NVIDIA_VISIBLE_DEVICES=2"
    volumes:
      - "${HOME}/CMPNet/MPnet:/root/code/MPnet"
      - "/tmp/data:/root/code/data"
      - "${HOME}/RLplayground/BC:/root/code/BC"
    command: bash
