version: '2.3'
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    image: cmpnet
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${HOME}/CMPNet/MPnet:/root/code/MPnet"
      - "/tmp/data:/root/code/data"
      - "${HOME}/RLplayground/BC:/root/code/BC"
    command: bash
